name: simulation
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install iverilog
        run: sudo apt-get install iverilog
      - name: Set up brimstone repo
        uses: actions/checkout@v1
      - name: Run all testbenches
        run: make