name: Testing
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install iverilog
        uses: sudo apt-get install iverlog
      - name: Run all testbenches
        run: make