name: Testing
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install iverilog
        run: sudo apt-get install iverilog
      - name: Run all testbenches
        run: make